// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hanhkzezwwqyugjpemgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbmhremV6d3dxeXVnanBlbWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4OTA5NTgsImV4cCI6MjA1OTQ2Njk1OH0.irsY-SfBvvtN8tsgU4U_O-wsh3fT5waJ5YKZ6IJQqzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
